### ISSUE TITLE
First Design Wireframes

### ISSUE THREAD

**Issue by steven-king** [steven-king/J390#5]
Please upload your PDF file to your github account (suggest creating a repo for your app) and post a comment with a direct link to the PDF.

**Comment by wesleyhitson** [comment]
I couldn't figure out how to add a PDF, so hopefully this jpeg will work!

https://cloud.githubusercontent.com/assets/7849882/9611485/e718861c-50ad-11e5-823a-26ba89e9048f.jpg

**Comment by hjjweiss** [comment]
Not sure how to add as PDF either...

(https://cloud.githubusercontent.com/assets/13887309/9637169/4e4c06d2-516d-11e5-9a43-fd3d315d5034.png)

**Comment by steven-king** [comment]
The JPEG image is fine. But if you want to use PDFs, go to file, export
select PDF.

**Comment by Jkotansky** [comment]
https://github.com/Jkotansky/app1/blob/master/wire_frame.pdf

**Comment by ghost** [comment]
PDF isn't one of the options in the Export dropdown. File -> Save a Copy will let you choose PDF though.
https://github.com/aila293/MyCBT/blob/master/screens.png

(I think I've way overestimated how big the font size should be.)

**Comment by parth9615** [comment]
https://github.com/parth9615/ListApp

**Comment by nickyromero** [comment]
![iphone 6 plus copy 2](https://cloud.githubusercontent.com/assets/13067895/9645180/21ef9402-5198-11e5-8a9d-7b76bcd2d77f.png)
![iphone 6 plus copy 3](https://cloud.githubusercontent.com/assets/13067895/9645181/21f302ea-5198-11e5-9870-aa3c697651db.png)
![iphone 6 plus copy](https://cloud.githubusercontent.com/assets/13067895/9645183/21f71c9a-5198-11e5-89af-7e2309506dcb.png)
![iphone 6 plus](https://cloud.githubusercontent.com/assets/13067895/9645182/21f50360-5198-11e5-9edc-8b83125e0c3a.png)

**Comment by brmayes** [comment]
https://github.com/brmayes/j390/blob/master/Wireframe-Imgs/views-combined.png (!!!!) 

Go meeeeeeee!

**Comment by lexinamer** [comment]
https://github.com/lexinamer/digitalshoebox_repo/blob/master/WireframeV1_Setup.pdf

Wooooo!

**Comment by inkhk** [comment]
https://github.com/inkhk/J390app/blob/master/designcomp.pdf

**Comment by andyroberson** [comment]
https://github.com/andyroberson/j390/blob/master/wireframe-design1.pdf

**Comment by jjliao2** [comment]
https://github.com/jjliao2/j390/blob/master/Food%20App%20Wireframe.pdf

**Comment by saigeso** [comment]
https://github.com/nowens4795/jomcapp/blob/master/nathan_owens_wireframe.pdf

**Comment by lindsaycarbonell** [comment]
http://lmcarbonell.com/wp-content/uploads/2015/09/lindsay_wireframe1.pdf
created the repo but the link isn't working...anyway uploaded it to my website as well

**Comment by wgmiller** [comment]
![wire frame](https://cloud.githubusercontent.com/assets/7349618/9651258/fc60807c-51db-11e5-9f7c-245348192a3a.png)

looks better when full screened

**Comment by nancygao** [comment]
https://github.com/nancygao/JOMC-390-/blob/fd4b1f63bb7181ca2ec798007b6ad8e5f35a66be/Desktop/Wireframe%20JOMC.pdf

**Comment by pillaim** [comment]
https://github.com/pillaim/planner-app/blob/master/Wireframing_Planner_App.pdf

**Comment by bhwarren** [comment]
https://github.com/bhwarren/PhotoCal/raw/master/phoneapp.pdf
