### ISSUE TITLE
App first UI Turn In

### ISSUE THREAD

**Issue by steven-king** [steven-king/J390#8]
Please post a comment with your project link.
ex. https://share.appgyver.com/?id=77499&hash=37f6c9a72ff458048e51920d20a8137376fab766777a068a64495aee9d41faf2&device_type=iphone

**Comment by lindsaycarbonell** [comment]
https://share.appgyver.com/?id=77850&hash=c979071cbdaa61bb29ace5800deca50d4d2653622dc788ce526cae78e3887fb2&device_type=iphone

**Comment by bhwarren** [comment]
https://share.appgyver.com/?id=77851&hash=2005c1290e6fd2c859101824ea1462835d009b55a7f019e9810f8571f3e5b869

**Comment by Jkotansky** [comment]
https://share.appgyver.com/?id=76662&hash=454c5235b958772a0249f3cbd6ca39d48b255e46b08a952beb63af34ce5a437e&token=938a4c17fa22616fa0556b5146192c1b

**Comment by wesleyhitson** [comment]
3D Mover: https://share.appgyver.com/?id=77854&hash=5b233f4804677353cdbe9ea5aa190639efeaf36e0ffb0195e44e54c8e44788b5&device_type=iphone

**Comment by lexinamer** [comment]
Digital Shoebox: https://share.appgyver.com/?id=76655&hash=7902a08b5def9b2fab2913df14a32ad665164c16f3b956733a1f413a06938ec9&token=f78c95a29562fa26b142127433f8b893

**Comment by pillaim** [comment]
https://share.appgyver.com/?id=77852&hash=f70fc594a32517a387a9d3c7c895b84331a0ccc6bf43e4921ca863039028eadb&device_type=iphone

**Comment by jjliao2** [comment]
https://share.appgyver.com/?id=76664&hash=de033c56b8c1f882a9236543a91c8777b951ef0a653478de71f9e42d95ac58cc&token=ac91b2327ce6e69d29dd42114bd2f3b8

**Comment by wgmiller** [comment]
https://share.appgyver.com/?id=77853&hash=ad97ae95dc2fc5578cc164a49cd1231731100fdc2ef3531e6b85aa6039496ce1

**Comment by andyroberson** [comment]
https://share.appgyver.com/?id=77856&hash=c75fdacf48bf7500fea110ca6cd565db38650ce6a19dfe5657ee02d6c099dfe9

**Comment by hjjweiss** [comment]
https://share.appgyver.com/?id=76660&hash=6d093e2c6a7eab97f5a1d19ada294afa2879d74a6901c3c218baef940ec77bc4&token=499db60f0773581e2e710d19f956deaa

**Comment by inkhk** [comment]
https://share.appgyver.com/?id=77855&hash=ace7bdd8ca2d9a904f8a9ef19c41998f2dcc4af69f691f866aecdfc3b151380c&device_type=iphone

**Comment by ghost** [comment]
Is a post about what to do with native apps forthcoming? Or have I missed it somewhere?

**Comment by saigeso** [comment]
https://share.appgyver.com/?id=78213&hash=f778f0ce341f7fde89c7a6efd4f0811af3add7b8463851b4eaf58096a6ca014e
